name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get CPM
        uses: neacsum/configurator@v0.0.11
        with:
          name: cpm.exe
          url: https://github.com/neacsum/cpm/releases/latest/download/cpm.exe

      - name: Create dependencies directory
        shell: cmd
        run: |
          if not exist "build\.dep-cache" mkdir "build\.dep-cache"

      - name: Build dependencies
        run: cpm -v --proto https -r build\.dep-cache

      - name: Create symlink for utpp
        shell: cmd
        run: |
          mklink /D build\.dep-cache\utpp-repo-src build\.dep-cache\utpp

      - name: Build and run tests
        shell: cmd
        run: |
          build.bat tests

      - name: Save tests result
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: build/exe/x64/debug/utf8_tests.xml
